### ISSUE TITLE
Error cannot read property 'toLowerCase'

### ISSUE THREAD

**Issue by NektariosFifes** [ajaxtown/theme-document#2]
When i  write a draft on admin panel this error shows up and i cannot publish the draft.
`TypeError: Cannot read property 'toLowerCase' of undefined
    at toSlug (/home/nektarios-fifes/letterpad/letterpad/src/shared/slugify.ts:9:6)
    at Object.slugify (/home/nektarios-fifes/letterpad/letterpad/src/shared/slugify.ts:19:10)
    at Object.<anonymous> (/home/nektarios-fifes/letterpad/letterpad/src/api/models/post.ts:142:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/nektarios-fifes/letterpad/letterpad/src/api/models/post.ts:5:58)
error.message : Cannot destructure property `cover_image_width` of 'undefined' or 'null'.

[error]  api/server.ts:  Cannot destructure property `cover_image_width` of 'undefined' or 'null'. { code: 'INTERNAL_SERVER_ERROR',
  exception:
   { stacktrace:
      [ 'TypeError: Cannot destructure property `cover_image_width` of \'undefined\' or \'null\'.',
        '    at normalizePost (/home/nektarios-fifes/letterpad/letterpad/src/api/resolvers/post.js:418:7)',
        '    at /home/nektarios-fifes/letterpad/letterpad/src/api/resolvers/post.js:349:30',
        '    at Generator.next (<anonymous>)',
        '    at fulfilled (/home/nektarios-fifes/letterpad/letterpad/src/api/resolvers/post.js:5:58)' ] } } { [GraphQLError: Cannot destructure property `cover_image_width` of 'undefined' or 'null'.]
  message:
   'Cannot destructure property `cover_image_width` of \'undefined\' or \'null\'.',
  locations: [ { line: 2, column: 3 } ],
  path: [ 'updatePost' ],
  extensions:
   { code: 'INTERNAL_SERVER_ERROR',
     exception: { stacktrace: [Array] } } } {"message":"Cannot destructure property `cover_image_width` of 'undefined' or 'null'.","locations":[{"line":2,"column":3}],"path":["updatePost"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot destructure property `cover_image_width` of 'undefined' or 'null'.","    at normalizePost (/home/nektarios-fifes/letterpad/letterpad/src/api/resolvers/post.js:418:7)","    at /home/nektarios-fifes/letterpad/letterpad/src/api/resolvers/post.js:349:30","    at Generator.next (<anonymous>)","    at fulfilled (/home/nektarios-fifes/letterpad/letterpad/src/api/resolvers/post.js:5:58)"]}}}
`

**Comment by abhisaha1** [comment]
Yea, its the same for this as well. I could not update this theme. For now only the `hugo` theme will work.

**Comment by NektariosFifes** [comment]
ok
